FROM tiangolo/uvicorn-gunicorn-fastapi:python3.6

WORKDIR /app
COPY . /app/
RUN pip install -r requirements.txt
RUN pip install -r requirements.dev.txt
#RUN python init_db.py
#RUN alembic upgrade head
