name: Dockerize  Backend
on:
  push:
    branches:
      - master
# https://github.com/marketplace/actions/publish-docker
# https://github.com/docker/build-push-action
defaults:
  run:
    working-directory: .
jobs:
  deploy:
    name: Dockerize Backend Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
#      - name: Create Node Environment
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install
      #- run: npm install -g  yarn
      #- run: yarn install
      #- run: yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
          id: docker_build
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            push: true
            tags: latest
            #context: ./backend
            dockerfile: Dockerfile
            registry: docker.io
            image: radxrad/oasis_backend_prod
            target: backend
      - name: Build and push backend
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          push: true
          tags: latest
          #context: ./backend
          dockerfile: Dockerfile
          registry: docker.io
          image: radxrad/oasis_backend_prod
          target: frontend
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
