name: Deploy to gh-page
on:
  push:
    branches:
      - stella_ui_dev
# https://github.com/marketplace/actions/publish-docker
# https://github.com/docker/build-push-action
defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    name: deploy gh-pages using npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run:  |
        git config --global user.name 'valentinedwv'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        npm run deploy
      env:
        user_name: 'valentinedwv'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
