name: Deploy to gh-page
on:
  push:
    branches:
      - ghdeploy
# https://github.com/marketplace/actions/publish-docker
# https://github.com/docker/build-push-action
defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: deploy gh-pages using npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: npm install
      - name: build deploy
        run: npm run deploy
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
    env:
      user_name: 'valentinedwv'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      github_token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
